### ISSUE TITLE
Document zone and node ordering for uniform meshes

### ISSUE THREAD

**Issue by adayton1** [LLNL/conduit#1033]
I'm attempting to use Conduit's mesh blueprint protocol in an application, and I was wondering what order is implied by uniform meshes as it relates to a field array.

It's probably easier to explain what I mean with some drawings (pretend each number is the ID of a zone, left/right is the x axis, and up/down is the y axis).

Order by x, then y
6   7   8
3   4   5
0   1    2

Order by y, then x
2   5   8
1   4   7
0   3   6

I would image the order affects the layout of the field arrays.

**Comment by cyrush** [comment]
Yes, we should document - but the quickest answer is to view it in VisIt to see how field values vary with the logical mesh

**Comment by adayton1** [comment]
Thanks for the tip!

**Comment by adayton1** [comment]
Is there a way to say certain indices in a field array correspond to ghost data? Or do I just need to allocate a new array with only the data on the current domain?

**Comment by cyrush** [comment]
check out the strided structured example:

https://github.com/LLNL/conduit/blob/56bee65f4f5db1c1d0cfba5b062484ff2870c409/src/libs/blueprint/conduit_blueprint_mesh_examples.hpp#L57

This is a newer concept -- the striding isn't yet supported in VisIt. 

In many use cases we use a field that identifies ghosts and then use that field to threshold when we want to get rid of ghosts.

**Comment by cyrush** [comment]
Here is a python example you can use to see the order:
```
import conduit

yaml = """
    coordsets: 
      coords: 
        type: "uniform"
        dims: 
          i: 4
          j: 4
    topologies: 
      topo: 
        type: "uniform"
        coordset: "coords"
    fields: 
      id: 
        association: "element"
        topology: "topo"
        values: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]
"""
data = conduit.Node()
data.parse(yaml,"yaml");
conduit.relay.io.blueprint.save_mesh(data,"example","hdf5");
```


![Screen Shot 2022-11-02 at 5 12 34 PM](https://user-images.githubusercontent.com/1194526/199625458-e1a3f900-ab37-4ef6-a6b9-f3b02cb24fc4.png)
