### ISSUE TITLE
adjset validator tool 

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#1097]
we have utils to paint adjsets on to meshes for visual debugging - but we should also consider creating a tool that validates adjsets across domains and identifies any possible issues.

**Comment by BradWhitlock** [comment]
I need this too so I started writing one at [adjset_verifier](https://github.com/LLNL/conduit/blob/feature/whitlock/adjset_verifier_tool/src/executables/adjset_verify/adjset_verify.cpp). It's a serial prototype that loads a root file and makes sure all domains have the same adjset names. Then for vertex association adjsets, it will look up the local coordinate for a vertex that is a member of an adjset. Then it attempts to see if such as coordinate exists in the neighbor domain. If not, it is flagged as an error.

**Comment by cyrush** [comment]
Awesome.  For the I/O, can you use `load_mesh` or are you aiming to do partial I/O (one domain at time)?

I ask b/c there are more complex cases than the file_pattern + tree_pattern now.

If you do need partial I/O, we may want to make the Blueprint Path Generator public for use in a utility like this.

Also did the paint methods help you view counts across domains with VisIt?

**Comment by BradWhitlock** [comment]
I guess I did not know `load_mesh` to read the root file. I mostly think of `load()` when I think about relay. Partial I/O would probably be desirable for a large problem and this program would need to evolve toward being a parallel program that loads a subset of domains. This started quick&dirty.

**Comment by BradWhitlock** [comment]
I made an adjset::validate method for serial and parallel and the new conduit_adjset_validate tool is using the serial version. It uses load_mesh too now.

**Comment by BradWhitlock** [comment]
Example of running it on some output of one of the new CI tests:

```
../../executables/adjset_validate/conduit_adjset_validate -input adjset_validate_element_3d_bad.root
Check adjset main_adjset... FAIL: The adjsets contain errors.

domain_000000: 
  main_adjset: 
    domain0_1: 
      - 
        message: "Domain 0 adjset main_adjset group domain0_1: element 0 could not be located in neighbor domain 1."
        element: 0
        neighbor: 1
domain_000001: 
  main_adjset: 
    domain0_1: 
      - 
        message: "Domain 1 adjset main_adjset group domain0_1: element 2 could not be located in neighbor domain 0."
        element: 2
        neighbor: 0
```
