### ISSUE TITLE
is this multi-buffer material set example correct?

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#1132]
```
#     z0       z1       z2
# +--------+--------+--------+
# | a0     | a1 ___/|        |
# |___-----|----    |   b2   |
# |     b0 |     b1 |        |
# +--------+--------+--------+
#

matsets:
  matset:
    topology: topology
    volume_fractions:
      a:
        values: [0, 0, 0, a1, 0, a0]
        indices: [5, 3]
      b:
        values: [0, b0, b2, b1, 0]
        indices: [1, 3, 2]
    material_map: # (optional)
      a: 0
      b: 1
```

Is this example missing element ids ? Otherwise how do we know `z2` does not have material `a`?

https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#multi-buffer-material-sets
