### ISSUE TITLE
Multiple Silo cycles without suffix

### ISSUE THREAD

**Issue by ibaned** [llnl/conduit#1200]
Hello!

I am trying to write multiple cycles to Silo without having them end up as separate directories and proliferating files. So far I have two calls to `conduit::relay::mpi::io::silo::write_mesh` with `opts` as follows:

first:
```yaml
file_style: "multi_file"
suffix: "none"
number_of_files: 1
root_file_ext: "silo"
truncate: "true"
silo_type: "hdf5"
```

second:
```yaml
file_style: "multi_file"
suffix: "none"
number_of_files: 1
root_file_ext: "silo"
silo_type: "unknown"
```

I get the rather cryptic error:
```
DBMkDir: Low-level function call failed: mesh
```

How can I get multiple cycles of multi-domain meshes into a set of Silo files where the number of files is at most proportional to the number of domains and not multiplied by the number of cycles as well?

Thanks!
