### ISSUE TITLE
Mesh blueprint element windings polyhedral topologies

### ISSUE THREAD

**Issue by jappa** [LLNL/conduit#1281]
The element windings for polyhedral topologies can't be described correctly using the current Mesh blueprint.  The dual pyramid based example for polyhedral topologies defines the common quad face using a single winding which is correct for element 1 and incorrect for element 0.

One solution would be to add an orientation section to the elements section that specifies if the winding needs to be reversed for any given subelement.

Are there any plans to address this?

**Comment by cyrush** [comment]
@jappa I understand this issue, windings are complex to capture. 

In practice we try to follow VTK windings, but the Blueprint does not explicitly impose or encode winding info. 

Downstream codes are usually imposing their own checks. 

We did try to come up with a broadly applicable solution - but didn't arrive a something we were happy with.
We are open to ideas, but need multiple client code cases to check against.

**Comment by jappa** [comment]
I noticed that the current dual pyramid polyhedra example is incorrect for VTK client code. VTK assumes all faces surrounding a polyhedral cell point outwards.  For the current blueprint to work any shared faces between polyhedral elements need to be duplicated and reordered to give the correct orientation but this significantly increases the size of the dataset.

This could be addressed with something like 
```
topologies:
  topology:
    coordset: coords
    type: unstructured
    elements:
      shape: polyhedral
      connectivity: [0, 1, 2, 3, 4, 0, 5, 6, 7, 8]
      orientation: [-1, 1, 1, 1, 1, 1, 1, 1, 1, 1] # -> Added orientation
      sizes: [5, 5]
      offsets: [0, 5]
    subelements:
      shape: polygonal
      connectivity: [1, 2, 4, 3, 1, 2, 0, 2, 4, 0, 4, 3, 0, 3, 1, 0, 1, 2, 5, 2, 4, 5, 4, 3, 5, 3, 1, 5]
      sizes: [4, 3, 3, 3, 3, 3, 3, 3, 3]
      offsets: [0, 4, 7, 10, 13, 16, 19, 22, 25]
```

I can provide example datasets for testing if required and happy to contribute to adding the feature to the code
