### ISSUE TITLE
use some sort of `self` construct to allow blueprint index to survive renames?

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#1295]
```
blueprint_index: 
  mesh: 
    state: 
      time: 0.0
      path: "mesh/state"
      number_of_domains: 1
      partition_pattern: "example_yaml.root:/"
    coordsets: 
      coords: 
        type: "uniform"
        coord_system: 
          axes: 
            x: 
            y: 
            z: 
          type: "cartesian"
        path: "mesh/coordsets/coords"
    topologies: 
      topo: 
        type: "uniform"
        coordset: "coords"
        path: "mesh/topologies/topo"
protocol: 
  name: "yaml"
  version: "0.9.2"
number_of_files: 1
number_of_trees: 1
file_pattern: "example_yaml.root"
tree_pattern: "/"
```

When someone renames example_yaml.root to something else, the patterns are broken.

Ideas?
```
   partition_pattern: "{self}:/"
```

```
file_pattern: "{self}"
```

or empty refers to self?
