### ISSUE TITLE
update mesh utils iterator to support shape_map style mixed element meshes

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#1301]
Old stream id concept is now deprecated, so update the ele iterator to support shape maps style meshes:

https://github.com/LLNL/conduit/blob/c990a81953f222b90da30a390a7380849a625ad1/src/libs/blueprint/conduit_blueprint_mesh_utils_iterate_elements.hpp#L220

Note: this code underpins the partitioning

**Comment by mlohry** [comment]
I just found myself looking for this feature. I have mixed element meshes of hex/tet/pyramid/wedge, and partitioning this does appear to work, where it does work for a plain all-tet mesh.

**Comment by cyrush** [comment]
Add detection for new case , `shape: "mixed"`
```
9. Mixed shape topology 3 -- using shape_map
  topo:
    coordset: (String name of coordset)
    type: unstructured
    elements:
        shape: "mixed"
        shape_map: (names to ids)
        shapes: (integer array with shape ids for each element)
        sizes: (integerarray with number of indices per element)
        offsets: (integer array of offsets for each element)
        connectivity: (integer array of vertex ids)
```
