### ISSUE TITLE
Cannot output external data

### ISSUE THREAD

**Issue by eschnett** [LLNL/conduit#1383]
I am using Conduit 0.9.3.

I am creating a tree of nodes and want to output the respective structure to an HDF5 file (or to yaml etc.) I find that the nodes themselves are output, but the data stored in the nodes is not output. (These should be arrays of doubles.)

I am using this code:
```C++
            const std::string varname =
                CCTK_VarName(groupdata.firstvarindex + var);
            conduit::Node &node_var = node_group[varname];

            assert(cgroup.grouptype == CCTK_GF);
            const amrex::MultiFab &mfab = *groupdata.mfab[timelevel];
            const amrex::FArrayBox &fab = mfab[component];
            assert(cgroup.vartype == CCTK_VARIABLE_REAL);
            const CCTK_REAL *const dataptr = fab.dataPtr(var);
            const std::size_t numpoints = fab.numPts();

            const conduit::DataArray<CCTK_REAL> dataarray(
                dataptr,
                conduit::DataType(conduit_datatype_id<CCTK_REAL>(),
                numpoints));

            node_var["data"].set_external(dataarray);
            // node_var["data"].set(dataarray);

            // node_var["data"].set_external(
            //     conduit::DataType(conduit_datatype_id<CCTK_REAL>(), numpoints),
            //     const_cast<CCTK_REAL *>(dataptr));
            // node_var["data"].set(
            //     conduit::DataType(conduit_datatype_id<CCTK_REAL>(), numpoints),
            //     const_cast<CCTK_REAL *>(dataptr));
```

This leads to the following output:
```yaml
m0000: 
  rl00: 
    c00000000: 
      COORDINATESX::VERTEX_COORDS: 
        vcoordx: 
          data:
        vcoordy: 
          data:
        vcoordz: 
          data:
      MULTIPATCHWAVETOY::STATE: 
        phi: 
          data:
        Pi: 
          data:
        Dx: 
          data:
        Dy: 
          data:
        Dz: 
          data:
      MULTIPATCHWAVETOY::ENERGY: 
        energy: 
          data:
```

Each of the `data` nodes should hold an array but it doesn't. I have tried summary output, yaml output, and HDF5, and they all behave the same.

I find that if I change the `set_external` to `set`, then the data is output. However, I don't want to make a copy of the data since these are large arrays.

I have also tried setting the node without creating a `DataArray` first. (These are the commented-out lines further down.) I assume the behaviour should be identical. However, in this case the data are never output, neither with `set` nor with `set_external`.
