### ISSUE TITLE
Provide a more intuitive strided structured example mesh

### ISSUE THREAD

**Issue by JustinPrivitera** [LLNL/conduit#1397]
The strides for element associated fields should be in terms of elements. This example makes it seem as though strides are always the same for topologies, vertex-associated fields, and element-associated fields. I think we should change the example to make it clear.

```python
mesh = conduit.Node()
desc = conduit.Node()
conduit.blueprint.mesh.examples.strided_structured(desc, 4, 3, 2, mesh)
```
```yaml
state: 
  time: 3.1415
  cycle: 100
coordsets: 
  coords: 
    type: "explicit"
    values: 
      x: [-10.0, -6.66666666666667, -3.33333333333333, ..., 6.66666666666667, 10.0]
      y: [-10.0, -10.0, -10.0, ..., 10.0, 10.0]
      z: [-10.0, -10.0, -10.0, ..., 10.0, 10.0]
topologies: 
  mesh: 
    type: "structured"
    coordset: "coords"
    elements: 
      dims: 
        i: 3
        j: 2
        k: 1
        offsets: [2, 2, 2]
        strides: [1, 7, 42]
fields: 
  vert_vals: 
    association: "vertex"
    topology: "mesh"
    offsets: [2, 2, 2]
    strides: [1, 7, 42]
    values: [0.0, 0.0, 0.0, ..., 0.0, 0.0]
  ele_vals: 
    association: "element"
    topology: "mesh"
    offsets: [2, 2, 2]
    strides: [1, 7, 42]
    values: [0.0, 0.0, 0.0, ..., 0.0, 0.0]
```
The example isn't _wrong_, just misleading.
