### ISSUE TITLE
add support for strided structured source meshes to `to_unstructued`

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#1436]

**Comment by cyrush** [comment]
<img width="745" height="647" alt="Image" src="https://github.com/user-attachments/assets/676af6df-8951-4c31-aef8-0503c64838c7" />

above, strided structured example
below, current to_unstructued result

**Comment by cyrush** [comment]
Input:
```
state: 
  time: 3.1415
  cycle: 100
coordsets: 
  coords: 
    type: "explicit"
    values: 
      x: [-10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0]
      y: [-10.0, -10.0, -10.0, -10.0, -10.0, -10.0, -10.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
topologies: 
  mesh: 
    type: "structured"
    coordset: "coords"
    elements: 
      dims: 
        i: 3
        j: 2
        offsets: [2, 2]
        strides: [1, 7]
fields: 
  vert_vals: 
    association: "vertex"
    topology: "mesh"
    offsets: [2, 2]
    strides: [1, 7]
    values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 4.0, 0.0, 0.0, 0.0, 5.0, 6.0, 7.0, 8.0, 0.0, 0.0, 0.0, 9.0, 10.0, 11.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  ele_vals: 
    association: "element"
    topology: "mesh"
    offsets: [2, 2]
    strides: [1, 7]
    values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 0.0, 0.0, 0.0, 0.0, 4.0, 5.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```

Result:

```
topologies: 
  mesh: 
    type: "unstructured"
    coordset: "coords"
    elements: 
      shape: "quad"
      connectivity: [0, 1, 5, 4, 1, 2, 6, 5, 2, 3, 7, 6, 4, 5, 9, 8, 5, 6, 10, 9, 6, 7, 11, 10]
coordsets: 
  coords: 
    type: "explicit"
    values: 
      x: [-10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0]
      y: [-10.0, -10.0, -10.0, -10.0, -10.0, -10.0, -10.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
fields: 
  vert_vals: 
    association: "vertex"
    topology: "mesh"
    offsets: [2, 2]
    strides: [1, 7]
    values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 4.0, 0.0, 0.0, 0.0, 5.0, 6.0, 7.0, 8.0, 0.0, 0.0, 0.0, 9.0, 10.0, 11.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  ele_vals: 
    association: "element"
    topology: "mesh"
    offsets: [2, 2]
    strides: [1, 7]
    values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 0.0, 0.0, 0.0, 0.0, 4.0, 5.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
state: 
  time: 3.1415
  cycle: 100
```
