### ISSUE TITLE
passing multi-dimensional array

### ISSUE THREAD

**Issue by uturuncoglu** [LLNL/conduit#1446]
I wonder if there is any example that demonstrates sending multi-dimensional array back and forth between Fortran and Python.

**Comment by cyrush** [comment]
@uturuncoglu  for round trip with the multi-d context, you will have to provide and manage additional shape information yourself.

We have an `ndarray` spec, where we use `shape`, along with optional `offset` and `stride`.  These entries are stored as additional conduit nodes. 
```
values - actuall data
shape - dims
stride - optional strides per dim
offset - optional additional indirection at start of each dim
```
Here is an example of a C++ object that helps with indexing in these cases:

https://github.com/LLNL/conduit/blob/554373f4bd4ffdfbd5bb9c43ac6152ed4c856f57/src/libs/blueprint/conduit_blueprint_ndarray_index.hpp#L66

For numpy cases and fortran, the shape, offset, and stride could be used to construct a native nd representation - but we don't have direct support for that in conduit.

**Comment by uturuncoglu** [comment]
@cyrush Thanks for the clarification. It makes sense. I was wondering about direct support for multi-dimensional array s but this also works for me.

**Comment by uturuncoglu** [comment]
@cyrush Sorry for opening this issue again but do I need to define shape, stride and offset under field or it would be defined in topologies/mesh section. It is not clear in the `conduit_blueprint_ndarray_index.hpp`. Is there any simple node output for it? So, I could reference it.

**Comment by cyrush** [comment]
@uturuncoglu sorry I missed this issue. we have tests for the ndarray index here:

https://github.com/LLNL/conduit/blob/554373f4bd4ffdfbd5bb9c43ac6152ed4c856f57/src/tests/blueprint/t_blueprint_ndarray_index.cpp

the NDIndex accepts a node that has `shape` `offset` and `stride`

Shape is required, `offset` and `stride` are optional.

As far as how strides and ND shape fits into a blueprint mesh, please see the "strided structured" example mesh, here is an example:

Note: the shape is always derived from the topology, this example shows different ways to provide offsets and strides.

```
import conduit
n = conduit.Node()
conduit.blueprint.mesh.examples.generate("strided_structured",n)
print(n.to_yaml())
```

 ```
state: 
  time: 3.1415
  cycle: 100
coordsets: 
  coords: 
    type: "explicit"
    values: 
      x: [-10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0, -10.0, -6.66666666666667, -3.33333333333333, 4.44089209850063e-16, 3.33333333333333, 6.66666666666667, 10.0]
      y: [-10.0, -10.0, -10.0, -10.0, -10.0, -10.0, -10.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -6.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0]
topologies: 
  mesh: 
    type: "structured"
    coordset: "coords"
    elements: 
      dims: 
        i: 3
        j: 2
        offsets: [2, 2]
        strides: [1, 7]
fields: 
  vert_vals: 
    association: "vertex"
    topology: "mesh"
    offsets: [2, 2]
    strides: [1, 7]
    values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 4.0, 0.0, 0.0, 0.0, 5.0, 6.0, 7.0, 8.0, 0.0, 0.0, 0.0, 9.0, 10.0, 11.0, 12.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  ele_vals: 
    association: "element"
    topology: "mesh"
    offsets: [2, 2]
    strides: [1, 7]
    values: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 0.0, 0.0, 0.0, 0.0, 4.0, 5.0, 6.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
