### ISSUE TITLE
refactor polygonal/polyhedral layout

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#504]
In order to improve interoperability with client codes, the data layout for Conduit-Blueprint's polygonal/polyhdral elements needs to be updated. Specifically, the layout needs to be changed from an in-line, stream-based sequence to an out-of-line, offset-based collection of sequences. This can be accomplished by adopting Conduit's new one-to-many schema (#511) to extract the polygon sizes from the index stream.

#### Polygonal Variables ####

- `eI`: number of vertices in 2D element I
- `eIvJ`: the index of vertex J in element I

#### Current Layout ####

```
topology:
  coordset: coords
  type: unstructured
  elements:
    shape: polygonal
    connectivity: [e1, e1v1, ..., e1ve1, e2, e2v1, ..., e2ve2, ...]
```

#### New Layout ####

```
topology:
  coordset: coords
  type: unstructured
  elements:
    shape: polygonal
    connectivity: [e1v1, ..., e1ve1, e2v1, ..., e2ve2, ...]
    sizes: [e1, e2, e3, ...]
    offsets: [0, e1, e1+e2, ...]
```

This situation changes slightly in 3D because the top-level, out-of-line `begins` sequence does not fully describe the internal structure of an arbitrary element (e.g. how the faces that comprise the 3D element are laid out). For such cases, an extra offset-based sequence needs to be generated.

#### Polygonal Variables ####

- `eI`: number of sub-elements in 3D element I
- `eIsJ`: the index of sub-element (face) J of 3D element I
- `sIvJ`: the index of vertex J in sub-element (face) I 
- `|eIsJ|`: number of vertices in sub-element (face) J of 3D element I
- `eI_sJ_vK`: the index of vertex K in sub-element J in element I

#### Current Layout ####

```
topology:
  coordset: coords
  type: unstructured
  elements:
    shape: polyhedral
    connectivity: [e1, |e1_s1|, e1_s1_v1, ..., e1_s1_vs1, ..., |e1_se1|, e1_se1_v1,  ..., e1_se1_vse1, e2, ...]
```

#### New Layout ####

```
topology:
  coordset: coords
  type: unstructured
  elements:
    shape: polyhedral
    connectivity: [e1s1, ..., e1se1, e2s1, ..., e2se2, ...]
    sizes: [e1, e2, e3, ...]
    offsets: [0, e1, e1+e2, ...]
  subelements:
    shape: polygonal
    connectivity: [s1v1, ..., s1vs1, s2vs1, ..., s2vs2, ...]
    sizes: [s1, s2, s3, ...]
    offsets: [0, s1, s1+s2, ...]
```

In order to help illustrate the meaning of this refactoring, here are the [Blueprint polygonal/polyhedral examples](https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#polygonal-polyhedral-topologies) in the new format:

#### Example Diagram ####

```
       4-----5
       |`\   |
 e1 -> |  \  | <- e0
       |   \.|
       7-----6
```

#### New Layout ####

```
topology:
  coordset: coords
  type: unstructured
  elements:
    shape: polygonal
    connectivity: [4, 6, 5, 7, 6, 4]
    sizes: [3, 3]
    offsets: [0, 3]
```

#### Example Diagram ####

```
         0
        /|\
       / | \ <- e0
      /  |  \
     /_.-3-._\
    1.,  |  ,.4
     \ `'2'` /
      \  |  /
 e1 -> \ | /
        \|/
         5
```

#### New Layout ####

```
topology:
  coordset: coords
  type: unstructured
  elements:
    shape: polyhedral
    connectivity: [0, 1, 2, 3, 4, 0, 5, 6, 7, 8]
    sizes: [5, 5]
    offsets: [0, 5]
  subelements:
    shape: polygonal
    connectivity: [1, 2, 4, 3, 0, 1, 2, 0, 2, 4, 0, 3, 4, 0, 1, 3, 5, 1, 2, 5, 2, 4, 5, 3, 4, 5, 1, 3]
    sizes: [4, 3, 3, 3, 3, 3, 3, 3, 3]
    offsets: [0, 4, 7, 10, 13, 16, 19, 22, 25, 28]
```
