### ISSUE TITLE
extend/generalize one-to-many indexing schemes

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#511]
Many of the associations between the different segments of Conduit's Blueprint hierarchy encode one-to-many relationships between these different segments. For example, a Blueprint topology encodes the individual associations between higher-level entities (e.g. `quad`s) and the many coordinates that comprise these entities. In order to support the widest possible set of internally-used and client-specified one-to-many relationships with minimal added complexity, the following additions are proposed for these relationships in the Blueprint:

### One-to-Many Schema ###

```
onetomany: # placeholder object name
  values: [ ... ] # the base array for the one-to-many encoding
  sizes: [ ... ] # for each 'one', the length of the 'many'
  offsets: [ ... ] # for each 'one', the starting index of the 'many' list
  indices: [ ... ] # for each 'one', the locations of the 'many' by index in 'values'
```

### One-to-Many Components ###

- `values`: This is the base array for the one-to-many relationship. Hopefully, this array can be zero-copied from a host code due to the indexing flexibility afforded by the other one-to-many schema components.
- `sizes`: The `i`th index in this array is the number of 'many' items associated with `i`th 'one'. If not specified, this component will default to indicating 1 as the length of each 'many'. This component must be provided if the `offsets` component is specified.
- `offsets`: The `i`th index in this array is the index of the first of the 'many' value for the `i`th 'one'. This 'many' index refers to an entry in the `indices` array (which operates as a pass-through to `values` if not provided). If not provided, this component will operate as though all the 'one' relationships are consecutive and compacted (i.e. `values[indices[i]]` is the first 'many' for the `i`th 'one'). This component must be provided if the `sizes` component is specified.
- `indices`: The `offsets[i]`th value in this array is the first of the `size[i]` 'many' indices in `values` associated with the `i`th 'one'. If not provided, this component will act as a pass-through index to `values` (i.e. `indices[i] == i`).

#### Polygonal Topology ####

```
topology:
  coordsets: coords
  type: unstructured
  elements:
    shape: polygonal
    # pentagon, (filler), quad, (filler), tri
    connectivity: [0, 1, 2, 3, 4, -1, -1, 5, 6, 7, 8, -1, -1, 9, 10, 11]
    sizes: [5, 4, 3]
    offsets: [0, 7, 13]
```

#### Sparse Field ####

```
field:
  association: element
  volume_dependent: false
  topology: topology
  # (filler), e2, (filler), e0, (filler), e1
  values: [-1.0, -1.0, -1.0, 2.0, -1.0, 0.0, -1.0, -1.0, 1.0]
  indices: [5, 8, 3]
```

### Notes ###

- The one-to-many extensions (i.e. `offsets`, `sizes`, `indices`) always annotate the one-to-many arrays that exist at the same level of the Blueprint hierarchy. The name of these arrays will vary based on context (e.g. `volume_fractions` for a `matset`, `connectivity` for an unstructured `topology`, etc.).
- The `sizes`/`offsets` extensions are orthogonal to the `indices` extension. These two sets of extensions can be used in concert, but also operate sensibly in standalone contexts (see examples above).

**Comment by agcapps** [comment]
For a fixed size of "many" (say, a collection of `k` triangles), perhaps allow `sizes` to be a scalar.  That way you would store one 3 instead of a length-`k` array with a 3 in each element.

**Comment by cyrush** [comment]
@agcapps yes, the current way to specify a topology supports this already, here is an example:

```
topologies: 
        mesh: 
          type: "unstructured",
          coordset: "coords",
          elements: 
            "shape": "tri",
            "connectivity": [0, 5, 6, 0, 1, 6, 1, 6, 7, 1, 2, 7, 2, 7, 8, 2, 3, 8, 3, 8, 9, 3, 4, 9, 5, 10, 11, 5, 6, 11, 6, 11, 12, 6, 7, 12, 7, 12, 13, 7, 8, 13, 8, 13, 14, 8, 9, 14, 10, 15, 16, 10, 11, 16, 11, 16, 17, 11, 12, 17, 12, 17, 18, 12, 13, 18, 13, 18, 19, 13, 14, 19, 15, 20, 21, 15, 16, 21, 16, 21, 22, 16, 17, 22, 17, 22, 23, 17, 18, 23, 18, 23, 24, 18, 19, 24]
```

note: we have to use shape names b/c sizes are ambiguous in some cases ( "tet" vs "quad")

**Comment by cyrush** [comment]
@agcapps but I can see your case as well for general support, if we do go with that I recommend `size`, to explicitly specify the many vs `sizes`

**Comment by agcapps** [comment]
@cyrush true: I think the use case(s) I thought of will all be fulfilled by the named "shape" node.

**Comment by xjrc** [comment]
Thinking more in-depth about this feature and how it interacts with the rest of the Blueprint, I've discovered some cases that need to be more carefully fleshed out. There are two in particular that come to mind: (1) defining a one-to-many indexing scheme on a vector field and (2) defining a one-to-many indexing scheme on a single-buffer material array (#513).

Considering the former case, a one-to-many index may be used on a vector field that's sparsely or non-uniformly defined, or even one that's stored in a single-buffer scheme. All of these cases are common for vector fields with many components (and, for that matter, materials), so I think it's a use case we should consider. Such a field would currently be defined like one of the following:

#### Multi-Buffer ####

```
fields:
  vector_field:
    association: element,
    topology: mesh,
    volume_dependent: false,
    values:
      x: [ ... ],
      y: [ ... ],
      z: [ ... ],
```

#### Single-Buffer ####

```
fields:
  vector_field:
    association: element,
    topology: mesh,
    volume_dependent: false,
    values: [ ... ],
    component_ids: [ ... 0, ... 1, ... 2, ... ],
    component_map:
      x: 0,
      y: 1,
      z: 2,
```

For the single-buffer definition (which is identical to the single-buffer material case), an idea we've floated for supporting a one-to-many index is to have the `sizes`, `offsets`, and `indices` component qualifiers apply uniformly to all arrays at a given level of the hierarchy. In the example above, this means applying to both `values` and `component_ids` in the same way. This works great for the single-buffer case, but complicates the multi-buffer case as the level at which the `size`, `offsets`, and `indices` qualifiers would be defined is the same as the vector components, which makes their intent ambiguous.

There are at least two potential solutions to this problem: (1) allow for nesting in multi-material and vector field cases to eliminate ambiguity between components and one-to-many qualifiers or (2) restrict the component names so that `sizes`, `offsets`, and `indices` aren't allowed as material/field names. These solutions would look something like the following:

#### Nesting Solution ####

```
fields:
  vector_field:
    association: element,
    topology: mesh,
    volume_dependent: false,
    values:
      x:
        values: [ ... ],
        sizes: [ ... ],
        offsets: [ ... ],
        indices: [ ... ],
      y:
        values: [ ... ],
        sizes: [ ... ],
        offsets: [ ... ],
        indices: [ ... ],
      z:
        values: [ ... ],
        sizes: [ ... ],
        offsets: [ ... ],
        indices: [ ... ],
```

#### Naming Solution ####

```
fields:
  vector_field:
    association: element,
    topology: mesh,
    volume_dependent: false,
    values:
      x: [ ... ],
      y: [ ... ],
      z: [ ... ],
      sizes: [ ... ],
      offsets: [ ... ],
      indices: [ ... ],
```

Of course, even if we choose the latter solution, there are still situations where the structure of the former solution may be preferred instead (e.g. if the components don't share a sparsity scheme, which is common at least for multi-buffer materials). Since shared components could be zero-copied in the worst case, I think I prefer the nesting solution, so it's what I'm going to target in my implementation.

This thought was long and possibly incoherent, so please let me know if anyone has any questions or comments related to the contained ideas. I believe @cyrush and I had a discussion about this already in the context of single-buffer materials and came to the same conclusion, but I wanted to derive and document the issue and justification all the same!

**Comment by xjrc** [comment]
Here's the latest schema for `matsets` entries that I've concocted, which I believe covers both the single and split buffer cases:

### Example Diagram ###

```
    z0       z1       z2
    +--------+--------+--------+
    | a0     | a1 ___/|        |
    | __-----|----    |   b2   |
    |/    b0 |     b1 |        |
    +--------+--------+--------+
```

### Matset Examples ###

#### Full Single Buffer ####

```
matsets:
  matset:
    topology: topology
    volume_fractions:
      values: [a0, a1, 0, b0, b1, b2]
      material_ids: [1, 1, 1, 2, 2, 2]
      material_map:
        a: 1
        b: 2
        c: 0
```

#### Full Split Buffer ####

```
matsets:
  matset:
    topology: topology
    volume_fractions:
      values:
        a: [a0, a1, 0]
        b: [b0, b1, b2]
```

#### Sparse Single Buffer ####

```
matsets:
  matset:
    topology: topology
    volume_fractions:
      values: [0, a0, b2, b1, b0, 0, a1, 0]
      material_ids: [0, 1, 2, 2, 2, 0, 1, 0]
      material_map:
        a: 1
        b: 2
        c: 0
      sizes: [2, 2, 1]
      offsets: [0, 2, 4]
      indices: [1, 4, 6, 3, 2]
```

#### Sparse Split Buffer ####

```
matsets:
  matset:
    topology: topology
    volume_fractions:
      values:
        a:
          values: [0, 0, a1, 0, a0]
          indices: [4, 2]
        b:
          values: [b0, 0, 0, b1, 0, 0, b2]
          indices: [0, 3, 6]
      element_ids:
        a: [0, 1]
        b: [0, 3, 6]
```

The same rules could be analogously applied to the `fields` section, but it does lead to rather inelegant path requirements (i.e. `fields/field/values/values`, `fields/field/matset_values/values`). This can perhaps be fixed by updating the top-level paths (e.g. breaking it into `fields/field/aggregate` and `fields/field/permaterial` or something instead). Also, there's some decisions to be made in how to handle multi-component, per-material fields with a single buffer scheme, but those decisions are complicated and largely unimportant so I'd prefer to defer them for later.

**Comment by rhornung67** [comment]
@xjrc you are a master of ASCII art 👍

**Comment by xjrc** [comment]
@rhornung67: Thank you! If you'd like a piece for any machine login/code startup banners, I take commissions!

**Comment by agcapps** [comment]
Two questions about the "sparse split buffer" example.

1. I don't understand why `matsets/matset/volume_fractions/element_ids/b` has value [0, 3, 6].  Shouldn't it be [0, 1, 2], because that array is indexing into `matsets/matset/volume_fractions/values/b/indices` ?

2. Just to confirm, would the following be a less-complicated (but also valid) example of a sparse split buffer?
```
matsets:
  matset:
    topology: topology
    volume_fractions:
      values:
        a:
          values: [a1, a0]
        b:
          values: [b0, b1, b2]
      element_ids:
        a: [1, 0]
        b: [0, 1, 2]
```

**Comment by xjrc** [comment]
@agcapps

>     1. I don't understand why `matsets/matset/volume_fractions/element_ids/b` has value [0, 3, 6].  Shouldn't it be [0, 1, 2], because that array is indexing into `matsets/matset/volume_fractions/values/b/indices` ?

You are correct; thank you for catching that! I'll edit my original post to rectify this mistake.

>     2. Just to confirm, would the following be a less-complicated (but also valid) example of a sparse split buffer?

This is a great question! I have to think about this one a bit as its validity is based on some design decisions we need to make about when sparsity is applied. My initial reaction is to say that this example isn't valid because the isolated one-to-many relationship defined by `values/a/values` is incomplete (since none of `sizes`, `offsets` or `indices` are defined, they are all defaulted to assume a direct one-to-one relationship with the topology, which leaves us with too few values). On the other hand, always requiring `index` for sparsity means that `element_ids` can be redundant (as is the case with `element_ids/b` above). I'm going to have another look at some of the simulation examples I've got written down and see if I can come up with some sensible and intuitive rules!

**Comment by agcapps** [comment]
Thanks @xjrc .  After looking again at my question 2, I think I am really asking the following:

Why are the `element_ids` pulled out of `volume_fractions/values/a` and `b`, instead of being named `offsets` next to sibling `values` and `indices`?

**Comment by xjrc** [comment]
Ah, okay; I think I understand now! The reason we can't substitute `element_ids/a` for `values/a/values/offsets` is because these two paths have fundamentally different meanings. Specifically, the former is used to indicate the zone index for each material (i.e. `element_ids/a[i]` yields the zone index for the `i`th value in material `a`'s list)  while the latter indicates the one-to-many relationship start index for each material in the material array (i.e. `a/offests[i]` yields the position in `a/values` for the start of the `i`th one-to-many of materials to zones).

To illustrate the difference, here's an example that uses both `element_ids` and `offsets`:

#### Example Diagram ####

```
    z0       z1       z2
    +--------+--------+--------+
    |        |        |\  a0   |
    |   b0   |   b1   | ------ |
    |        |        |   b2  \|
    +--------+--------+--------+
```

#### Example Materials ####

```
matsets:
  matset:
    topology: topology
    volume_fractions:
      values:
        a:
          values: [-1, -1, -1, a0, -1]
          sizes: [1]
          offsets: [3]
        b:
          values: [-1, -1, b2, b1, b0]
          indices: [4, 3, 2]
      element_ids:
        a: [2]
        b: [0, 1, 2]
```
