### ISSUE TITLE
add material-dominant relationship support to blueprint materials

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#512]
The Blueprint schema currently only supports the **zone-dominant** topology-material relationship model, which is the model wherein the **zone is used as the index for the data** in the relationship. Many client codes prefer using a **material-dominant** relationship, which organizes the data so that the **data indexes into the zone list** instead. Fortunately, these concepts are fundamentally compatible and can both be supported with minimal changes to the Blueprint model.

That being said, the following schema extension to the `matsets` section of the Blueprint is proposed to enable material-dominant relationship types:

```
matsets:
  matset:
    topology: topology
    volume_fractions:
      # individual material is an object, so we know handling is different
      matI: [vf1, ..., vfN]
    element_ids:
      # element_ids: index into 'topology' where zi is the zone for vfi
      element_ids: [z1, ..., zN],
```

**Comment by xjrc** [comment]
It's important to note that this change will be compatible with the index changes proposed in #511 and is related to the material sparsity ideas being pursed in #506.

**Comment by xjrc** [comment]
@cyrush, @agcapps: After pondering the implementation of this extension in `blueprint::mesh::matset::verify`, I've got an open question for both of you: should a `matset` be allowed to be both uni-buffer and material-dominant? Consider the following "potentially conforming" structure:

#### Example Diagram ####

```
    z0       z1       z2
    +--------+--------+--------+
    |        |        |\  a0   |
    |   b0   |   b1   | ------ |
    |        |        |   b2  \|
    +--------+--------+--------+
```

#### Material-Dominant Uni-Buffer Representation ####

```
matsets:
  matset:
    topology: topology
    volume_fractions: [-1, -1, a0, -1, b1, -1, -1, b0, b2]
    material_ids: [0, 0, 1, 0, 2, 0, 0, 2, 2]
    material_map:
      a: 1
      b: 2
      c: 0
    sizes: [2, 1, 1]
    offsets: [0, 2, 3]
    indices: [2, 8, 4, 7]
    element_ids: [2, 1, 0]
```

The abstract part of my brain says that this schema is fine because it can be derived completely from existing rules, but my pragmatic side says that this is too confusing and adds too little functionality wise (e.g. `element_ids` wouldn't have to exist if `indices` were arranged in ascending zone order). What do both of you think? Is this something we should support for maximum flexibility, or reject to reduce surface area?
