### ISSUE TITLE
add single-buffer support to blueprint materials

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#513]
The current layout of the `matsets` section of the Blueprint schema requires that each material in a `matset` be specified as an object entry (e.g. `matset/volume_fractions/material`) with an individual buffer. In order to support clients using a non-trivial single-buffer allocation, the extensions in #511 and a few supplemental extensions can be integrated into the `matsets` specification.

The set of proposed supplemental entries for a single-buffer `matset` is as follows:

- `material_ids`: A parallel array to the single-buffer list of material volume fractions that associates these volume fractions with material identifiers.
- `material_names`: An object that associates material names (keys) with material identifiers (values).

Integrating these extensions, a single-buffer `matsets` entry will have the following structure:

```
matsets:
  matset:
    topology: topology
    material_names:
      material_name: material_id
    volume_fractions: [vf1, ..., vfN]
    material_ids: [m1, ..., mN]
```

In order to better illustrate how this feature could be used, here's an example:

#### Example Diagram ####

```

    z0       z1       z2
+--------+--------+--------+
| a0     | a1 ___/|        |
| __-----|----    |   b2   |
|/    b0 |     b1 |        |
+--------+--------+--------+

```

#### Example Schema ####

```
matsets:
  matset:
    topology: topology
    material_names:
      a: 1
      b: 2
      c: 0
    volume_fractions: [0, a0, b2, b1, b0, 0, a1, 0]
    material_ids: [0, 1, 2, 2, 2, 0, 1, 0]
    sizes: [2, 2, 1]
    offsets: [0, 2, 4]
    indices: [1, 4, 6, 3, 2]
```

**Comment by cyrush** [comment]
we might also consider: 

material_names ==> material_map

```
matsets:
  matset:
    topology: topology
    material_map:
      a: 1
      b: 2
      c: 0
    volume_fractions: [0, a0, b2, b1, b0, 0, a1, 0]
    material_ids: [0, 1, 2, 2, 2, 0, 1, 0]
    sizes: [2, 2, 1]
    offsets: [0, 2, 4]
    indices: [1, 4, 6, 3, 2]
```
