### ISSUE TITLE
determine final names for `o2mrelation` functions

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#564]
Before a new point version of Conduit is deployed, the names for the new `blueprint::o2mrelation` property/query functions should be reviewed and finalized. The current names for these functions and their respective roles are outlined below:

#### `o2mrelation::query_paths(const Node&, Node&)` ####

Given an `o2mrelation` node (the first argument), this function returns a node (via the second argument) that contains all of the data paths to which the `o2mrelation` meta components (e.g. `sizes`) apply.

```
o2m:
  values: [float64]
  relation: [int32]
  metadata:
    paths: [char8]
    domain: int32
  sizes: [int32]
  offsets: [int32]
  indices: [int32]
n: (empty)

== query_paths(o2m, n) ==

n:
  values: (empty)
  relation: (empty)
```

#### `o2mrelation::to_compact(Node&)` ####

Given an `o2mrelation` node (the first argument), adjust the `offsets` parameter of this `o2mrelation` to reflect that the relationship data is contiguous and compacted.

```
o2m:
  values: [1.0, 2.0, 2.0, 3.0, 3.0, 3.0]
  sizes: [1, 2, 3]
  offsets: [0, 0, 0]

== to_compact(o2m) ==

o2m:
  values: [1.0, 2.0, 2.0, 3.0, 3.0, 3.0]
  sizes: [1, 2, 3]
  offsets: [0, 1, 3]
```
