### ISSUE TITLE
conduit::blueprint::mesh::examples::basic should throw an error for nonsensical inputs.

### ISSUE THREAD

**Issue by SeifIbrahim** [LLNL/conduit#580]
For example:
`conduit::blueprint::mesh::examples::basic("tets", 3, 3, 0, data);`

tries to generate a tetrahedral mesh with 0 z-dimension and gives this output which causes unexpected errors later on:

```
coordsets: 
  coords: 
    type: "explicit"
    values: 
      x: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      y: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
topologies: 
  mesh: 
    type: "unstructured"
    coordset: "coords"
    elements: 
      shape: "tet"
      connectivity: 
fields: 
  field: 
    association: "element"
    topology: "mesh"
    volume_dependent: "false"
    values: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0]
```
