### ISSUE TITLE
Blueprint polyhedral documentation

### ISSUE THREAD

**Issue by nselliott** [LLNL/conduit#611]
In the example for the new polyhedral schema:

```
    #
    #         0
    #        /|\
    #       / | \ <- e0
    #      /  |  \
    #     /_.-3-._\
    #    1.,  |  ,.4
    #     \ `'2'` /
    #      \  |  /
    # e1 -> \ | /
    #        \|/
    #         5
    #|

    topologies:
      topology:
        coordset: coords
        type: unstructured
        elements:
          shape: polyhedral
          connectivity: [0, 1, 2, 3, 4, 0, 5, 6, 7, 8]
          sizes: [5, 5]
          offsets: [0, 5]
        subelements:
          shape: polygonal
          connectivity: [1, 2, 4, 3, 1, 2, 0, 2, 4, 0, 4, 3, 0, 3, 1, 0, 1, 2, 5, 2, 4, 5, 4, 3, 5, 3, 1, 5]
          sizes: [4, 3, 3, 3, 3, 3, 3, 3, 3]
          offsets: [0, 4, 7, 10, 13, 16, 19, 22, 25]
```

The `elements/connectivity` array should be  `[0, 1, 2, 3, 4, 5, 1, 2, 3, 4]`, as there are no vertices 6-8.

Related question:  Are there any rules for the ordering of the vertices for one element in the connectivity array?  In particular I am wondering about elements that are more complicated that regular tets/hexes.  Or does any order work as long as the faces are set up correctly in the subelements schema?
