### ISSUE TITLE
Documentation -- Example Triangle mesh has bad connectivity

### ISSUE THREAD

**Issue by gsjaardema** [LLNL/conduit#664]
On the https://llnl-conduit.readthedocs.io/en/latest/blueprint_mesh.html#tris example, I think that the connectivity for the "odd" numbered triangles is incorrect.  For all of the "even" triangles, the connectivity progresses clockwise around the element; for the "odd-numbered" triangles, the connectivity progresses counter-clockwise around the element.   I think that they should be consistent -- either all CW or all CCW.
```
topologies: 
  mesh: 
    type: "unstructured"
    coordset: "coords"
    elements: 
      shape: "tri"
      connectivity: [0, 3, 4, 0, 1, 4, 1, 4, 5, 1, 2, 5, 3, 6, 7, 3, 4, 7, 4, 7, 8, 4, 5, 8]
```
![image](https://user-images.githubusercontent.com/897294/100674988-5487f400-3323-11eb-9e33-df1091f23109.png)
