### ISSUE TITLE
Material-dominant uni-buffer matsets

### ISSUE THREAD

**Issue by nselliott** [LLNL/conduit#740]
I would just like some quick clarification on the proper way to describe a material-dominant uni-buffer matset.  The only material-dominant example in the documentation uses a multi-buffer.

```
 #     z0       z1       z2
 # +--------+--------+--------+
 # | a0     | a1 ___/|\___ c2 |
 # |___-----|----    |    ----|
 # |     b0 |     b1 | b2     |
 # +--------+--------+--------+
 #

 matsets:
  matset:
    topology: topology
    volume_fractions:
      a: [a0, a1]
      b: [b0, b1, b2]
      c: [c2]
    element_ids:
      a: [0, 1]
      b: [0, 1, 2]
      c: [2]
    material_map: # (optional)
      a: 0
      b: 1
      c: 2
```

If I re-arrange this as a uni-buffer like below, is this a complete valid description of the matset?

```
 matsets:
  matset:
    topology: topology
    volume_fractions: [a0,b0,a1,b1,b2,c2]
    material_ids: [0,1,0,1,1,2]
    element_ids: [0,0,1,1,2,2]
    material_map:
      a: 0
      b: 1
      c: 2
```
