### ISSUE TITLE
ndarray extension to fields 

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#755]
a few ideas I don't want to lose, so throwing them up here: 

using a ND array to define a field on a 2D structured mesh where assoc between field values and the elements is fully specified (vs blueprints implicit i,j relationship)

These examples are for a 10x10 element mesh:

scalar field:

```
field:
  values: [ lots of values] 
  topology: "topo"
  association: "element"
  shape: [ 10, 10]
  indices: [ "i","j"] # order corresponds to shape above, names matter
  strides: [ blah,blah] # optional
```

vector field:

```
field:
  values: [ lots of values] 
  topology: "topo"
  association: "element"
  shape: [ 10, 10, 3 ]
  indices: [ "i", "j", "v"] # order corresponds to shape above, "i" and "j" names matter
  strides: [ blah,blah,blah]  # optional
```

using a ND array to define a field o on an unstructured mesh where assoc between field values and the elements is fully specified (vs implicit id ->element relationship)

These examples are for a 100 element mesh:

scalar field:

```
field:
  values: [ lots of values] 
  topology: "topo"
  association: "element"
  shape: [ 100]
  indices: [ "id" ] # "id" name matters
  strides: [ blah,blah] # optional
```

vector field:

```
field:
  values: [ lots of values] 
  topology: "topo"
  association: "element"
  shape: [ 100, 3 ]
  indices: [ "id","v"] # "id" name matters
  strides: [ blah,blah] # optional
```
