### ISSUE TITLE
add pairwise option to `adjsets` information

### ISSUE THREAD

**Issue by xjrc** [LLNL/conduit#777]
In order to better support a number of codes, an option should be added to `adjsests` instances to specify whether their `groups` members are "pairwise" or "maximally shared." Given that these two representations are functionally equivalent, Conduit/Blueprint should support transformations between these representations as well. The example below demonstrates both of these representations:

#### Diagram ####

```
Y
 
^ (0, 2)
|   +-----------++-----------+
|   |           ||           |
|   |           ||           |
|   |  domain2  ||  domain3  |
|   |           ||           |
|   |           ||           |
|   +-----------++-----------+
|   +-----------++-----------+
|   |           ||           |
|   |           ||           |
|   |  domain0  ||  domain1  |
|   |           ||           |
|   |           ||           |
|   +-----------++-----------+
|                          (2, 0)
+----------------------------->  X
```

#### YAML ####

```
domain0:
  coordsets:
    cset:
      type: "explicit"
      values:
        x: [0.0, 1.0, 0.0, 1.0]
        y: [0.0, 0.0, 1.0, 1.0]
  topologies:
    elem_topo:
      coordset: "cset"
      type: "unstructured"
      elements:
        shape: "quad"
        connectivity: [0, 1, 3, 2]
domain1:
  coordsets:
    coords:
      type: "explicit"
      values:
        x: [1.0, 2.0, 1.0, 2.0]
        y: [0.0, 0.0, 1.0, 1.0]
  topologies:
    elem_topo:
      coordset: "cset"
      type: "unstructured"
      elements:
        shape: "quad"
        connectivity: [0, 1, 3, 2]
domain2:
  coordsets:
    coords:
      type: "explicit"
      values:
        x: [0.0, 1.0, 0.0, 1.0]
        y: [1.0, 1.0, 2.0, 2.0]
  topologies:
    elem_topo:
      coordset: "cset"
      type: "unstructured"
      elements:
        shape: "quad"
        connectivity: [0, 1, 3, 2]
domain3:
  coordsets:
    coords:
      type: "explicit"
      values:
        x: [1.0, 2.0, 1.0, 2.0]
        y: [1.0, 1.0, 2.0, 2.0]
  topologies:
    elem_topo:
      coordset: "cset"
      type: "unstructured"
      elements:
        shape: "quad"
        connectivity: [0, 1, 3, 2]
```

### Maximally Shared Adjset (Current) ### 

```
domain0:
  ...
  adjsets:
    elem_aset:
      topology: "elem_topo"
      association: "vertex"
      groups:
        group01:
          neighbors: [1]
          values: [1]
        group02:
          neighbors: [2]
          values: [2]
        group0123:
          neighbors: [1, 2, 3]
          values: [3]
domain1:
  ...
  adjsets:
    elem_aset:
      topology: "elem_topo"
      association: "vertex"
      groups:
        group01:
          neighbors: [0]
          values: [0]
        group13:
          neighbors: [3]
          values: [3]
        group0123:
          neighbors: [1, 2, 3]
          values: [2]
domain2:
  ...
  adjsets:
    elem_aset:
      topology: "elem_topo"
      association: "vertex"
      groups:
        group02:
          neighbors: [0]
          values: [0]
        group23:
          neighbors: [3]
          values: [3]
        group0123:
          neighbors: [1, 2, 3]
          values: [1]
domain3:
  ...
  adjsets:
    elem_aset:
      topology: "elem_topo"
      association: "vertex"
      groups:
        group13:
          neighbors: [1]
          values: [1]
        group23:
          neighbors: [2]
          values: [2]
        group0123:
          neighbors: [0, 1, 2]
          values: [0]
```

###  Pairwise Adjset (Proposal) ###

```
domain0:
  ...
  adjsets:
    elem_aset:
      topology: "elem_topo"
      association: "vertex"
      groups:
        group01:
          neighbors: [1]
          values: [1, 3]
        group02:
          neighbors: [2]
          values: [2, 3]
        group03:
          neighbors: [3]
          values: [3]
domain1:
  ...
  adjsets:
    elem_aset:
      topology: "elem_topo"
      association: "vertex"
      groups:
        group01:
          neighbors: [0]
          values: [0, 2]
        group02:
          neighbors: [2]
          values: [2]
        group13:
          neighbors: [3]
          values: [2, 3]
domain2:
  ...
  adjsets:
    elem_aset:
      topology: "elem_topo"
      association: "vertex"
      groups:
        group02:
          neighbors: [0]
          values: [0, 1]
        group12:
          neighbors: [1]
          values: [1]
        group23:
          neighbors: [3]
          values: [1, 3]
domain3:
  ...
  adjsets:
    elem_aset:
      topology: "elem_topo"
      association: "vertex"
      groups:
        group03:
          neighbors: [0]
          values: [0]
        group13:
          neighbors: [1]
          values: [0, 1]
        group23:
          neighbors: [2]
          values: [0, 2]
```

Tags: @bryujin, @cyrush
