### ISSUE TITLE
Braid triangle mesh should not accept three mesh dims?

### ISSUE THREAD

**Issue by mclarsen** [LLNL/conduit#842]
You can ask for a explicit triangle mesh `tris` and specify the dims as `20,20,20` but the resulting mesh only has a 2d coordinate system.

```
tate: 
  time: 3.1415
  cycle: 100
coordsets: 
  coords: 
    type: "explicit"
    values: 
      x: [-10.0, -8.94736842105263, -7.89473684210526, ..., 8.94736842105263, 10.0]
      y: [-10.0, -10.0, -10.0, ..., 10.0, 10.0]
```
