### ISSUE TITLE
mesh bp verify for index failure

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#962]
generated index fails due to `coord_system/type: "logical"`? 

here is a snippet:

```
blueprint_index: 
  mesh: 
    state: 
      path: "mesh/state"
      number_of_domains: 1
    coordsets: 
      coords: 
        type: "uniform"
        coord_system: 
          axes: 
            x: 
            y: 
          type: "logical"
        path: "mesh/coordsets/coords"

```

here is the failure:

```
Failed to find a valid Mesh Blueprint Index

mesh: 
  coordsets: 
    valid: "false"
    coords: 
      type: 
        valid: "true"
        info: 
          - "mesh::coordset::type: has valid value 'uniform'"
      path: 
        valid: "true"
      coord_system: 
        type: 
          valid: "false"
        errors: 
          - "mesh::coordset::coord_system: 'type' has invalid value 'logical'"
        axes: 
          valid: "true"
        valid: "false"
```

**Comment by cyrush** [comment]
in this case the coordset was presented is:

```
coordsets: 
  coords: 
    type: "uniform"
    dims: 
      i: 513
      j: 513
```
